repo: ''
canvasCourse: ''
canvasAssignment: ''

naming: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: 'index.html'
    valid: true
    bestPractices: true
    outline: true
    has:
      - ''
    has_not:
      - ''
    search:
      - ''
    search_not:
      - ''

css:
  - path: 'css/main.css'
    valid: true
    bestPractices: true
    has:
      - []
    has_not:
      - []
    search:
      - ''
    search_not:
      - ''

js:
  - path: 'js/main.js'
    valid: true
    bestPractices: true
    search:
      - ''
    search_not:
      - ''

screenshots:
  - path: 'index.html'
    sizes: [320, 400, 608, 980, 1440]

functionality:
  - path: 'index.html'
    noErrors: true
    tests:
      - |
